	<footer class="container-fluid text-center">
		<p>Redes Sociales:</p>
		<a href="https://www.facebook.com/" target="_blank"><img class="redes" src="multimedia/facebook.jpg" alt="imagen de facebook" /></a>
		<a href="https://www.instagram.com/?hl=es" target="_blank"><img class="redes" src="multimedia/instagram.png" alt="imagen de instagram" /></a>
		<a href="https://twitter.com/" target="_blank"><img class="redes" src="multimedia/twitter.png" alt="imagen de twitter" /></a>
		<a href="https://plus.google.com/discover" target="_blank"><img class="redes" src="multimedia/google.png" alt="imagen de google+" /></a>
		<p class="footer">Ejercicio de clase-Copyright &copy; 2019.</p>
	</footer>
