	<header>
		<img class="header" src="multimedia/header.png">
	</header>
	
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="main container">
				<a class="navbar-brand" href="https://es.wikipedia.org/wiki/Lenguaje_de_programaci%C3%B3n" target="_blank">
					Lengueje de progamación
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
			
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item ">
						<a class="nav-link" href="index.php">Inicio</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="javascript.php">JavaScript</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="java.php">Java</a>
					</li>
				</ul>
			</div>
			</div>
		</nav>